### ISSUE TITLE
looking for associated weight files

### ISSUE THREAD

**Issue by talhaanwarch** [leo7r/swiftface#2]
How can i find `yolov4_face.cfg` and `yolov4_face_final.weights` files

**Comment by leo7r** [comment]
I commited a new change, new names are `swiftface.cfg` and `swiftface.weights`

**Comment by talhaanwarch** [comment]
First i assumed the same until i got this error

`FileNotFoundError: Could not find module 'D:\rPPG\swiftface-master\swiftface-master\yolo_cpp_dll.dll' (or one of its dependencies). Try using the full path with constructor syntax`

Code to reproduce
```
import darknet
configPath = "swiftface.cfg"
weightPath = "swiftface.weights"

netMain = darknet.load_net_custom(configPath.encode(
            "ascii"), weightPath.encode("ascii"), 0, 1)  # batch size = 1
```

**Comment by leo7r** [comment]
@talhaanwarch did you install darknet? https://pjreddie.com/darknet/install/
